; Auto-generated. Do not edit!


(cl:in-package mouse_controller-msg)


;//! \htmlinclude mouse_sensors.msg.html

(cl:defclass <mouse_sensors> (roslisp-msg-protocol:ros-message)
  ((servo_pos_leg
    :reader servo_pos_leg
    :initarg :servo_pos_leg
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (servo_pos_aux
    :reader servo_pos_aux
    :initarg :servo_pos_aux
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (contact_sensors
    :reader contact_sensors
    :initarg :contact_sensors
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (imu_sensor
    :reader imu_sensor
    :initarg :imu_sensor
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass mouse_sensors (<mouse_sensors>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <mouse_sensors>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'mouse_sensors)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name mouse_controller-msg:<mouse_sensors> is deprecated: use mouse_controller-msg:mouse_sensors instead.")))

(cl:ensure-generic-function 'servo_pos_leg-val :lambda-list '(m))
(cl:defmethod servo_pos_leg-val ((m <mouse_sensors>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader mouse_controller-msg:servo_pos_leg-val is deprecated.  Use mouse_controller-msg:servo_pos_leg instead.")
  (servo_pos_leg m))

(cl:ensure-generic-function 'servo_pos_aux-val :lambda-list '(m))
(cl:defmethod servo_pos_aux-val ((m <mouse_sensors>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader mouse_controller-msg:servo_pos_aux-val is deprecated.  Use mouse_controller-msg:servo_pos_aux instead.")
  (servo_pos_aux m))

(cl:ensure-generic-function 'contact_sensors-val :lambda-list '(m))
(cl:defmethod contact_sensors-val ((m <mouse_sensors>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader mouse_controller-msg:contact_sensors-val is deprecated.  Use mouse_controller-msg:contact_sensors instead.")
  (contact_sensors m))

(cl:ensure-generic-function 'imu_sensor-val :lambda-list '(m))
(cl:defmethod imu_sensor-val ((m <mouse_sensors>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader mouse_controller-msg:imu_sensor-val is deprecated.  Use mouse_controller-msg:imu_sensor instead.")
  (imu_sensor m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <mouse_sensors>) ostream)
  "Serializes a message object of type '<mouse_sensors>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'servo_pos_leg))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'servo_pos_leg))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'servo_pos_aux))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'servo_pos_aux))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'contact_sensors))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'contact_sensors))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'imu_sensor))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'imu_sensor))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <mouse_sensors>) istream)
  "Deserializes a message object of type '<mouse_sensors>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'servo_pos_leg) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'servo_pos_leg)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'servo_pos_aux) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'servo_pos_aux)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'contact_sensors) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'contact_sensors)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'imu_sensor) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'imu_sensor)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<mouse_sensors>)))
  "Returns string type for a message object of type '<mouse_sensors>"
  "mouse_controller/mouse_sensors")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'mouse_sensors)))
  "Returns string type for a message object of type 'mouse_sensors"
  "mouse_controller/mouse_sensors")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<mouse_sensors>)))
  "Returns md5sum for a message object of type '<mouse_sensors>"
  "7a3639d3aca39f506211e62a51b3df2b")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'mouse_sensors)))
  "Returns md5sum for a message object of type 'mouse_sensors"
  "7a3639d3aca39f506211e62a51b3df2b")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<mouse_sensors>)))
  "Returns full string definition for message of type '<mouse_sensors>"
  (cl:format cl:nil "float32[] servo_pos_leg~%float32[] servo_pos_aux~%float32[] contact_sensors~%float32[] imu_sensor~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'mouse_sensors)))
  "Returns full string definition for message of type 'mouse_sensors"
  (cl:format cl:nil "float32[] servo_pos_leg~%float32[] servo_pos_aux~%float32[] contact_sensors~%float32[] imu_sensor~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <mouse_sensors>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'servo_pos_leg) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'servo_pos_aux) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'contact_sensors) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'imu_sensor) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <mouse_sensors>))
  "Converts a ROS message object to a list"
  (cl:list 'mouse_sensors
    (cl:cons ':servo_pos_leg (servo_pos_leg msg))
    (cl:cons ':servo_pos_aux (servo_pos_aux msg))
    (cl:cons ':contact_sensors (contact_sensors msg))
    (cl:cons ':imu_sensor (imu_sensor msg))
))
